### PR TITLE
Remove winit

### PR DESCRIPTION
**Pull request by Dinnerbone**
This fixes the fact that you can't go back and select a new swf

May need testing.

### CODE REVIEW

**Comment by torokati44** [comment]
Umm, I think switching away to a different app, then back, has regressed...? It restarts the movie now.

**Comment by Dinnerbone** [comment]
Should be fixed!

**Comment by torokati44** [comment]
Yep, switching away to a different app doesn't restart now - but also doesn't suspend emulation... 😅
Whatever, can be fixed later.

**Comment by torokati44** [comment]
Thanks a lot again! 😊

**Pull request merged**
